spring:
  datasource:
    #driver-class-name: org.h2.Driver
    #url: jdbc:h2:mem:pictgram
    #username: sa
    #password:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/pictgram
    username: board
    password: password

  h2:
    console:
      enabled: true
  
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

cloud:
  aws:
    stack:
      auto: false
    region:
      auto: false
      static: ap-northeast-1
      
onesignal:
  id: ${onesignal.id}
  